### ISSUE TITLE
Same state with different params passed to vue-router causes navigation/refresh

### ISSUE THREAD

**Issue by random-one** [zack24q/vue-navigation#7]
Is this so by design or it's me that expects too much from the module?
For example I have a route that has an `:id` param(like `/users/1`) and when I navigate from one to another(`/users/2`) a request to server with this `id` should be sent and an object should be retrieved. What happens now in `vue-navigation` is that it checks that the state name is the same(`users`), ignores the params and sends a refresh signal while the state should actually change.

**Comment by zack24q** [comment]
It follows the design of vue-router, [see this](https://router.vuejs.org/en/essentials/dynamic-matching.html), the same component instance will be reused.
Because the router component not change, so it is refresh signal. 
Tip: the refresh event parameter [`to`|`from`] also contains information, so you can know the page refresh `/users/1` to `/users/2`.

**Comment by random-one** [comment]
Thanks for the quick response. I will connect to the proper event and fix my code.
